# Hugging Face Token for Private Repository Access
# Copy this file to .streamlit/secrets.toml and add your actual token

HF_TOKEN = "your_huggingface_token_here"

# Instructions:
# 1. Go to https://huggingface.co/settings/tokens
# 2. Create a new token with "Read" permissions
# 3. Copy the token and replace "your_huggingface_token_here" above
# 4. Save this file as .streamlit/secrets.toml
# 5. Make sure .streamlit/secrets.toml is in your .gitignore file (already done)
